on: [push]

jobs:
  windup_job:
    runs-on: ubuntu-latest
    name: RHAMT
    steps:
      - uses: actions/checkout@v2
      - id: rhamt
        name: RHAMT
        uses: ./ # Uses an action in the root directory
        with:
          target: 'eap7'
          additional-command-line-arguments: '--sourceMode'
      - shell: bash
        run: |
          ls -l
      - name: Get the output time
        run: echo "The time was ${{ steps.rhamt.outputs.report }}"
      - name: Upload report
        uses: actions/upload-artifact@v1
        with:
          name: ${{ steps.rhamt.outputs.report }}
          path: ${{ steps.rhamt.outputs.report }}

