on: [push]

jobs:
  windup_job:
    runs-on: ubuntu-latest
    name: RHAMT
    steps:
      - uses: actions/checkout@v2
      - name: RHAMT
        uses: ./ # Uses an action in the root directory
        id: rhamt
        with:
          target: 'eap7'
          additional-command-line-arguments: '--sourceMode'
