on: [push]

jobs:
  windup_job:
    runs-on: ubuntu-latest
    name: RHAMT
    steps:
      - uses: actions/checkout@v2
      - id: rhamt
        name: RHAMT
        uses: ./ # Uses an action in the root directory
        with:
          target: 'eap7'
          additional-command-line-arguments: '--sourceMode'
      - name: list RHAMT
        run: ls -l ${{ steps.rhamt.outputs.output_folder }}
      - name: Prepare report
        shell: bash
        run: tar -czvf report.tgz ${{ steps.rhamt.outputs.output_folder }}
      - name: Upload report
        uses: actions/upload-artifact@v1
        with:
          name: report.tgz
          path: 'report.tgz'

