on: [push]

jobs:
  windup_job:
    runs-on: ubuntu-latest
    name: RHAMT
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        run: |
          expr 3 + 7 > math-homework.txt
      - shell: bash
        run: |
          pwd
      - shell: bash
        run: |
          ls -l
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v1
        with:
          name: homework
          path: math-homework.txt
      - id: rhamt
        name: RHAMT
        uses: ./ # Uses an action in the root directory
        with:
          target: 'eap7'
          additional-command-line-arguments: '--sourceMode'
      - shell: bash
        run: |
          ls -l
      - name: Set env
        run: echo ::set-env name=workspace::$GITHUB_WORKSPACE
      - shell: bash
        run: |
          ls -l ${{ env.workspace }}
      - name: Get the output time
        run: echo "The time was ${{ steps.rhamt.outputs.output_folder }}"
      - name: list RHAMT
        run: ls -l ${{ steps.rhamt.outputs.output_folder }}
      - name: Prepare report
        shell: bash
        run: tar -czvf report.tgz ${{ steps.rhamt.outputs.output_folder }}
      - name: Upload report
        uses: actions/upload-artifact@v1
        with:
          name: report.tgz
          path: 'report.tgz'

